config/routes.rb
TestSim::Application.routes.draw do
  root 'home#top'
  post '/result' => 'home#result'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def top
  end
   def result
   			#手の名前、ステータスの管理
			@hand = ["グー","チョキ","パー"]

			#プレイヤー（必殺の手,体力,攻撃,テクニック）
			#プレイヤー1を@a、プレイヤー2を@bと置く。
			@a = [params[:num1],params[:hpt1],params[:atk1],params[:tec1]].map{|w| w=w.to_i}
			@b = [params[:num2],params[:hpt2],params[:atk2],params[:tec2]].map{|w| w=w.to_i}


		   #攻撃と必殺技
		   def attack(playerx,playery)
		     playery[1] -= (playerx[2]*0.3).round
		     playery[1] = 0 if playery[1] < 0
		   end
		   def special(playerx,playery)
		     playery[1] -= (playerx[3]*0.6).round
		     playery[1] = 0 if playery[1] < 0
		   end

		    @log=["戦闘ログ"]
			#じゃんけんメソッドの定義
			#このnum1,num2はプレイヤーの必殺技でなく、それぞれのゲームごとの出した手である。
			@num1=[]
			@num2=[]
			@var=[]
			4.times do |n|
			@num1[n]=params[:a[0]]["#{n}"].to_i
			@num2[n]=params[:b[0]]["#{n}"].to_i
			#a[0]の0はじゃんけんの手の入力ということ。なぜかこうなっただけで特に意味は無い。num1[0]と["0"]における0は、1回目のバトルということ
			@log<< "1Pの手は" + @hand[@num1[n]]+ "です。"
			@log<< "2Pの手は" + @hand[@num2[n]]+ "です。"
				@var[n] = @num1[n] - @num2[n]
				if @var[n] == -1 || @var[n] == 2
					if @num1[n]==@a[n]
					  special(@a,@b)
					  @log<<"1Pの必殺技だ！"
					else
					  attack(@a,@b)
					  @log<<"1Pの攻撃！"
					end
				elsif @var[n] == 1 || @var[n] == -2
					if @num2[n]==@b[n]
					  special(@b,@a)
					  @log<<"2Pの必殺技だ！"
					else
					  attack(@b,@a)
					  @log<<"2Pの攻撃！"
					end
				elsif @var[n] == 0
				  	@log<<"あいこです"
				end
			@log<<"1Pの残り体力" + @a[1].to_s
			@log<<"2Pの残り体力" + @b[1].to_s
			break if @a[1]==0||@b[1]==0
			end
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/home.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>シキングシミュレーター！</title>
</head>
<body>
	<h1>ムシキングシミュレーター！</h1>
<%=yield%>
</body>
</html>

app/views/home/result.html.erb
 
    
    <% @log.each do |msg| %>
    <%=msg%><br>
    <%end%>

  <%if @a[1]==0&&@b[1]==0%>
    <%= "引き分け!"%>
  <%elsif @b[1]==0%>
    <%="1Pの勝ち！"%>
  <%elsif @a[1]==0%>
    <%= "2Pの勝ち！"%>
  <%else%>
    <%= "ゲーム終了に失敗。決着がつくように手を選んでください。"%>
<%end%>
<br>
<br>
<%=link_to '入力画面に戻る', '/'%>

app/views/home/top.html.erb
<h2>プレイヤー情報入力</h2>
<p>入力フォームに半角で入力してください。</p>
<%= form_tag result_path do %>
 <h3>プレイヤー1</h3>
   <p>
	必殺技を入力。<br>
    <input type="radio" name="num1" value="0" required checked>グー
    <input type="radio" name="num1" value="1" required>チョキ
    <input type="radio" name="num1" value="2" required>パー

   </p>
   <p>
   	体力のステータスを入力。<br>
    <input type="text" name="hpt1" value="10" required>
   </p>
   <p>
   	攻撃のステータスを入力。<br>
    <input type="text" name="atk1" value="100" required>
   </p>
   <p>
   	テクニックのステータスを入力。<br>
    <input type="text" name="tec1" value="100" required>
   </p>

 <h3>プレイヤー2</h3>
   <p>
	必殺技を入力。<br>
    <input type="radio" name="num2" value="0" required checked>グー
    <input type="radio" name="num2" value="1" required>チョキ
    <input type="radio" name="num2" value="2" required>パー
   </p>
   <p>
   	体力のステータスを入力。<br>
    <input type="text" name="hpt2" value="10" required>
   </p>
   <p>
   	攻撃のステータスを入力。<br>
    <input type="text" name="atk2" value="100" required>
   </p>
   <p>
   	テクニックのステータスを入力。<br>
    <input type="text" name="tec2" value="100" required>
   </p>
   <hr>
   <h2>試合内容入力</h2>
   <p>おたすけ、VA、あいこのダメージなどは実装されていません。</p>
   <%4.times do |n|%>
   <br><%=n+1%>試合目&nbsp;&nbsp;&nbsp;1P
   <input type="radio" name=<%="a[#{n}]"%> value="0" required checked>グー
   <input type="radio" name=<%="a[#{n}]"%> value="1" required>チョキ
   <input type="radio" name=<%="a[#{n}]"%> value="2" required>パー
   &nbsp;&nbsp;&nbsp; 2P
   <input type="radio" name=<%="b[#{n}]"%> value="0" required checked>グー
   <input type="radio" name=<%="b[#{n}]"%> value="1" required>チョキ
   <input type="radio" name=<%="b[#{n}]"%> value="2" required>パー
   <%end%>
   <br><br>
   <input type="submit" value="実験する" style="width:300px;height:200px;">
   <hr>
   <aside>ムシキング攻略！ All rights reserved.</aside>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestSim</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>シキングシミュレーター！</title>
</head>
<body>
	<h1>ムシキングシミュレータ！</h1>
<%=yield%>
</body>
</html>